require('core.options')
require('core.leader')
require('core.keymaps')
require('core.lsp')

require('plugins.mason')
require('plugins.lualine')
require('plugins.tokyonight')
require('plugins.ibl')
require('plugins.mini')
require('plugins.fyler')
require('plugins.fzf')
require('plugins.codeium')
require('plugins.blink')
require('plugins.aerial')

require('utility.opacity')
-- vim.pack.update()
