require('core.leader')
require('core.options')
require('core.keymaps')
require('core.lsp')

require('plugins.mason')
-- require('plugins.masonlspconfig')
require('plugins.mini')
require('plugins.codeium')
require('plugins.friendlysnip')
require('plugins.blink')
require('plugins.fzf')
require('plugins.emmet')
require('plugins.outline')
require('plugins.gitsigns')

require('plugins.smearcursor')
require('plugins.catppuccin')
require('plugins.bearded')
require('plugins.lualine')
require('plugins.neoscroll')

require('utility.opacity')
-- vim.pack.update()
